// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/spiritual-habits/HabitCard.tsx": () => import("../components/mockups/spiritual-habits/HabitCard.tsx"),
  "./components/mockups/spiritual-habits/JourneyPath.tsx": () => import("../components/mockups/spiritual-habits/JourneyPath.tsx"),
  "./components/mockups/spiritual-habits/StreakCalendar.tsx": () => import("../components/mockups/spiritual-habits/StreakCalendar.tsx"),
  "./components/mockups/spiritual-habits/TodayFirst.tsx": () => import("../components/mockups/spiritual-habits/TodayFirst.tsx"),
  "./components/mockups/spiritual-habits/WeeklyReport.tsx": () => import("../components/mockups/spiritual-habits/WeeklyReport.tsx")
};
