const colors = {
  light: {
    text: "#070F24",
    tint: "#C49B3C",
    background: "#F4F7FC",
    foreground: "#070F24",
    card: "#FFFFFF",
    cardForeground: "#070F24",
    primary: "#C49B3C",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF3FA",
    secondaryForeground: "#1A2B4A",
    muted: "#EEF3FA",
    mutedForeground: "#6B7994",
    accent: "#EEF3FA",
    accentForeground: "#070F24",
    destructive: "#F04444",
    destructiveForeground: "#FFFFFF",
    border: "#DCE5F0",
    input: "#DCE5F0",
    navBackground: "#0F1F3D",
    navForeground: "#FFFFFF",
    gold: "#C49B3C",
    silver: "#9AAAB8",
    bronze: "#A8714A",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#C49B3C",
    background: "#0F1F3D",
    foreground: "#FFFFFF",
    card: "#0B1729",
    cardForeground: "#FFFFFF",
    primary: "#C49B3C",
    primaryForeground: "#0F1F3D",
    secondary: "#1A2B4A",
    secondaryForeground: "#FFFFFF",
    muted: "#1A2B4A",
    mutedForeground: "#8BA5C5",
    accent: "#253659",
    accentForeground: "#FFFFFF",
    destructive: "#F04444",
    destructiveForeground: "#FFFFFF",
    border: "#253659",
    input: "#253659",
    navBackground: "#070F20",
    navForeground: "#FFFFFF",
    gold: "#D4A93C",
    silver: "#A0B4C8",
    bronze: "#B87D52",
  },
  radius: 8,
};

export default colors;
